### ISSUE TITLE
About Accelerometer and Gyroscope

### ISSUE THREAD

**Issue by whisperzh** [v1993/cemuhook-protocol#2]
Hello, your project is pretty nice and helpful!! But i get confused when it comes to Accelerometer and Gyroscope. I don't understand how the data is calculated. Is the data generated by one controller or boths?

**Comment by v1993** [comment]
What do you mean by

> by one controller or boths?

**Comment by whisperzh** [comment]
Ah,i fixed it by myself, sorry for the unclear expression
