### ISSUE TITLE
What are the touch position x and y max?

### ISSUE THREAD

**Issue by Filoppi** [v1993/cemuhook-protocol#4]
If I don't know their max values, how can I use it as a -1 to +1 mapping?
On DS4Windows it seems to be from 0 to 1919 on X and from 0 to 941 on Y, passed directly from the DS4 itself with no clamping nor mapping. Other implementation might pass it in whatever range they want. I'm sure they all start from 0 0 at the top left, but what will the bottom right be?

Edit: I can confirm the resolution is 1920x942 and you can trust this information.

**Comment by v1993** [comment]
That's a good question! I've never looked deeply into touch since it is less used feature of protocol.

If what you have dug from DS4Windows is indeed correct, mapping should be trivial (`+1*range/2`), but confirmation on this would be useful.

**Comment by Filoppi** [comment]
So 1919 and 941 are actually the max values returned by the DS4? If this standard doesn't allow to specify a touch x y max, other non-DS4 implementations should at least make an effort to remap their touch in DS4 space. Maybe that should be added to a new version of the standard, it shouldn't break previous versions.

**Comment by german77** [comment]
DS4Windows doesn't specify the maximum values. I do agree on adding that info in newer versions

**Comment by Filoppi** [comment]
I know it doesn't but maybe they are specified in some DS4 public document?

**Comment by v1993** [comment]
DSU protocol have no public document(s) as it was never intended to be used outside of original ("reference") implementation. That's the reason this reference had to be created. Specifically for touch, cemuhook (emulator side) itself never supported touchpad because other software already existed for mapping it to mouse at time.

Guess I'd better add note about implementation-defined touchpad coordinates. Keep this issue open until then,

**Comment by Filoppi** [comment]
I meant if Sony had released any documents on how to implement the DS4 as a device on Windows. In that case, I'm sure they would have specified the touch ranges, if not, it will definitely be in the PS4 SDK.

**Comment by Filoppi** [comment]
At the same time, forcing the switch touch screen to be mapped within DS4 ranges would lose quite a bit of accuracy, but that's the best we can do to keep compatibility until the standard offers a way to query information about the used device.

**Comment by v1993** [comment]
Actual programs that utilize touchscreen feature (Citra/Yuzu, I don't think anyone else does) allow to calibrate for touch ranges. As such, there is no compatibility with anything to keep by opting to use range from DS4Windows implementation (nothing I'm aware of expects it to be used).

I'll be sure to take this into account when working on replacement for DSU protocol.

**Comment by Filoppi** [comment]
Anyway if anyone cares, these seem to be the ranges of a real DS4:
![Calibration](https://user-images.githubusercontent.com/7011366/103881267-e2a18800-50e2-11eb-9716-70966de519bb.png)
