### ISSUE TITLE
Additions to the DSU protocol?

### ISSUE THREAD

**Issue by JJTech0130** [v1993/cemuhook-protocol#5]
Is there any way to propose additions to the DSU protocol? It seems to be widely implemented, but extremely limited due to it's DualShock-centric nature.

For example, it would be nice to provide:
+ Server specified buttons (and names?)
+ Rumble
+ Audio?

and probably other things.

**Comment by v1993** [comment]
> Server specified buttons (and names?)

Planned for eventual successor, would be impractical to add on top of existing protocol.

> Rumble

Introduced by #7 as an unofficial extension, also will be included in eventual successor.

> Audio?

Sounds (hah) out-of-scope for something intended to be an *input* protocol first and foremost. It really should be handled by other things.
